name: CI

on:
  pull_request:
    branches: ['**']
  push:
    branches:
      - main

jobs:
  # Job 1: Lint type checking.
  lint-typecheck:
    name: Lint & type-check
    runs-on: ubuntu-latest
    strategy: { matrix: { python-version: [ 3.13 ] } }
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install project (incl. dev deps)
        run: |
          pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.create false
          poetry install --no-interaction --no-ansi --with dev

      - name: Black — style check
        run: poetry run black --check .

      - name: Flake8 — lint
        run: poetry run flake8 .

  # Job 2: Run pytest on the GitHub runner.
  runner-tests:
    name: Tests on runner
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.13]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry and project dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.create false
          poetry install --no-interaction --no-ansi

      - name: Install pytest & local package
        run: |
          pip install pytest

      - name: Run pytest
        run: pytest --maxfail=1 --disable-warnings -q
